### ISSUE TITLE
Struggling with a new install

### ISSUE THREAD

**Issue by lnlyssg** [bpbradley/ansible-role-komodo#4]
I'm struggling to run this role using the example from the README. I'm trying to run it on an Ubuntu 24.04 server. The first attempt as my normal user ended with:

```
fatal: [komodo_periphery1]: FAILED! => {"changed": false, "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", "name": "komodo", "rc": 1}
```

I then tried with `become: true` and got

```
TASK [bpbradley.komodo : Stop periphery service] *****************************************************************
fatal: [komodo_periphery1]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:komodo:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.17/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user"}
```

I'm not sure how to proceed from here, any ideas?

**Comment by bpbradley** [comment]
Thanks for trying it out! This seems to be a permissions issue with the ansible control user.

Can you share your inventory files and playbook with the `become: yes` that you added?

There could be some weird double become situation going on. I can try to reproduce tomorrow.

**Comment by lnlyssg** [comment]
It's basically just like the readme, the inventory is currently just one of my test cloud servers:

```
komodo:
    hosts:
        komodo_periphery1:
            ansible_host: testing
```

and the playbook is also mostly like the readme:

```
---
- name: Manage Komodo Service
  hosts: komodo
  roles:
      - role: bpbradley.komodo
        become: true
        komodo_action: "install"
        komodo_version: "v1.17.0"
        passkey: !vault |
          xxxxx
```
